apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    name: config-server-svc
    app: library-service-app
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    name: config-server-pod
    app: library-service-app  
