apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    name: eureka-server-svc
    app: library-service-app
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    name: eureka-server-pod
    app: library-service-app
