apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deploy
  labels:
    name: user-service-deploy
    app: library-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-service-pod
      app: library-service-app
  template:
    metadata:
      name: user-service-pod  
      labels:
        name: user-service-pod
        app: library-service-app
    spec:
      containers:
        - name: user-service
          image: localhost:5000/user-service:latest
          ports:
            - containerPort: 8083
